soarair/views.py
from ast import keyword
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import Product, ProductCategory, Order
from datetime import datetime
from .forms import CheckoutForm
from . import db

bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    categories = ProductCategory.query.order_by(
        ProductCategory.name.desc()).all()
    newarrivals = Product.query.order_by(Product.date.desc()).limit(6)
    return render_template('index.html', categories=categories, newarrivals=newarrivals)


@bp.route('/shop/<int:categoryid>/')
def shop(categoryid):
    products = Product.query.filter(Product.category_id == categoryid)
    category = ProductCategory.query.filter(ProductCategory.id == categoryid)
    return render_template('shop.html', products=products, category=category)


@bp.route('/shop/new/<int:categoryid>/')
def shopnew(categoryid):
    products = Product.query.filter(Product.category_id == categoryid).order_by(
        Product.date.desc()).limit(5)
    category = ProductCategory.query.filter(ProductCategory.id == categoryid)
    return render_template('shop.html', products=products, category=category)


@bp.route('/shop/highrate/<int:categoryid>/')
def shophighrate(categoryid):
    products = Product.query.filter(Product.category_id == categoryid).filter(
        Product.rating == 5).all()
    category = ProductCategory.query.filter(ProductCategory.id == categoryid)
    return render_template('shop.html', products=products, category=category)


@bp.route('/product/<int:category>/<int:productid>/')
def product(category, productid):
    product = Product.query.filter(Product.id == productid)
    categoryid = ProductCategory.query.filter(
        ProductCategory.id == category)
    relatedprods = Product.query.filter(
        Product.category_id == category).filter(Product.id != productid).limit(3)
    return render_template('productDetails.html', product=product, categoryid=categoryid, relatedprods=relatedprods)


@bp.route('/search/')
def search():
    search = request.args.get('search')
    search1 = '%{}%'.format(search)  # substrings will match
    products = Product.query.filter(Product.description.like(
        search1) | Product.name.like(search1)).all()
    return render_template('shopsearch.html', products=products, keyword=search)


@bp.route('/order', methods=['POST', 'GET'])
def order():
    product_id = request.values.get('product_id')
   # retrieve order if there is one
    if 'order_id' in session.keys():
        order = Order.query.get(session['order_id'])
    # order will be None if order_id stale
    else:
        # there is no order
        order = None
    # create new order if needed
    if order is None:
        order = Order(status=False, firstname='', lastname='', street='', apartment='', state='', zip='',
                      email='', phone='', notes='', totalcost=0, totalpoints=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('failed at creating a new order')
            order = None

    # calcultate totalprice
    totalcost = 0
    if order is not None:
        for product in order.products:
            totalcost = totalcost + product.price

    # calcultate totalpoints
    totalpoints = 0
    if order is not None:
        for product in order.products:
            totalpoints = totalpoints + product.points

    if product_id is not None and order is not None:
        product = Product.query.get(product_id)
        if product not in order.products:
            try:
                order.products.append(product)
                db.session.commit()
            except:
                return 'There was an issue adding the item to your basket'
            return redirect(url_for('main.order'))
        else:
            flash('item already in basket')
            return redirect(url_for('main.order'))

    return render_template('order.html', order=order, cost=totalcost, point=totalpoints)

# Delete specific basket items


@bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id = request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        product_to_delete = Product.query.get(id)
        try:
            order.products.remove(product_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))


@bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All items deleted')
    return redirect(url_for('main.index'))


@bp.route('/checkout/<float:total_cost>/<int:total_points>/', methods=['POST', 'GET'])
def checkout(total_cost, total_points):
    form = CheckoutForm()
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])

        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.lastname = form.lastname.data
            order.street = form.street.data
            order.apartment = form.apartment.data
            order.state = form.state.data
            order.zip = form.zip.data
            order.email = form.email.data
            order.phone = form.phone.data
            order.notes = form.notes.data
            totalcost = 0
            totalpoints = 0
            for product in order.products:
                totalcost = totalcost + product.price
            order.totalcost = totalcost
            for product in order.products:
                totalpoints = totalpoints + product.points
            order.totalpoints = totalpoints
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                return redirect(url_for('main.thankyou'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form=form, order=order, tc=total_cost, tp=total_points)


@bp.route('/thankyou')
def thankyou():
    return render_template('thankyou.html')

soarair/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="static/images/Icons/logo.png">
    <meta name="description" content="Soarair Kids Shop">
    <title>Soarair | Kids Shop</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <!-- Start Header/ Navigation -->
    <header>
        <nav class="custom-navbar navbar navbar-expand-xl navbar-dark sticky-top" arial-label="Soarair navigation bar">

            <div class="container">
                <a class="navbar-brand" href="{{ url_for('main.index') }}">
                    <img src="{{url_for('static', filename='images/Icons/logo-white.png')}}" width="60" height="60"
                        alt="Soarair Kids" />
                    Kids Shop
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsSoarair"
                    aria-controls="navbarsSoarair" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-end" id="navbarsSoarair">
                    <ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
                        </li>
                        <li><a class="nav-link" href="#">About Us</a></li>
                        <li><a class="nav-link" href="#">Contact us</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="shopdropdown" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                Merchandise
                            </a>
                            <div class="dropdown-menu" aria-labelledby="shopdropdown">
                                <a class="dropdown-item" href="{{ url_for('main.shop', categoryid=2) }}">Apparel</a>
                                <a class="dropdown-item" href="{{ url_for('main.shop', categoryid=6) }}">Model/Toy</a>
                                <a class="dropdown-item" href="{{ url_for('main.shop', categoryid=5) }}">Bag/Luggage</a>
                                <a class="dropdown-item" href="{{ url_for('main.shop', categoryid=1) }}">Accessories</a>
                                <a class="dropdown-item" href="{{ url_for('main.shop', categoryid=4) }}">Flight
                                    Comforts</a>
                                <a class="dropdown-item" href="{{ url_for('main.shop', categoryid=3) }}">Back to
                                    School</a>
                            </div>
                        </li>
                    </ul>

                    <form class="form-search form-inline" action="{{url_for('main.search')}}">
                        <input id="search" type="search" name="search" placeholder="Type a keyword to search..." />
                    </form>

                    <ul class="custom-navbar-cta navbar-nav">
                        <li><a class="nav-link" href="#"><img
                                    src="{{url_for('static', filename='img/Icons/user-white.png')}}" width="30"
                                    height="30" alt="sign in icon"></a></li>
                        <li><a class="nav-link" href="{{url_for('main.order')}}"><img
                                    src="{{url_for('static', filename='img/Icons/cart-white.png')}}" width="30"
                                    height="30" alt="cart"></a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-warning" role="alert">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
        {% block head %}{% endblock %}
    </header>

    <main>
        {% block main %}{% endblock %}
    </main>
    <!-- Start footer section -->
    <footer class="footer-section">
        <div class="container">
            <div class="row g-5 my-3">
                <!-- Subscribe -->
                <div class="col-lg-4">
                    <h5>Subscribe</h5>
                    <p class="mb-4" style="font-size: 14px;">
                        Be the first to know about new Soarair kids products, kids programs, sales & promos by
                        submitting your email!
                        You can opt out at any time!
                    </p>
                    <div class="subscription-form">
                        <form class="form-check-inline">
                            <input class="form-control mb-2" type="search" placeholder="Email Address"
                                aria-label="Search">
                            <a type="submit"><span class="fa fa-paper-plane ml-2"></span></a>
                        </form>
                    </div>
                </div>

                <div class="col-lg-8">
                    <div class="row links-wrap">
                        <!-- Help and Support -->
                        <div class="col-12 col-sm-6 col-md-4 mb-4">
                            <h5>Help and Support</h5>
                            <ul class="list-unstyled">
                                <li><a href="#">About us</a></li>
                                <li><a href="#">Services</a></li>
                                <li><a href="#">Latest Newsletter</a></li>
                                <li><a href="#">Order Tracking</a></li>
                                <li><a href="#">More Soarair Loyalty Merchandise</a></li>
                            </ul>
                        </div>

                        <!-- Customer Service -->
                        <div class="col-12 col-sm-6 col-md-4 mb-4">
                            <h5>Customer Service</h5>
                            <ul class="list-unstyled">
                                <li><a href="#">FAQs</a></li>
                                <li><a href="#">Returns and Cancellations</a></li>
                                <li><a href="#">Terms & Conditions</a></li>
                                <li><a href="#">Orders & Shipping Policy</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                            </ul>
                        </div>

                        <!-- Connect with Us -->
                        <div class="col-12 col-sm-6 col-md-4 mb-4">
                            <h5>Connect With Us</h5>
                            <ul class="list-unstyled">
                                <li><a href="#">info@soarair.com</a></li>
                                <li>(123) 456 7890</li>
                                <li><a href="#">11 Queens Street, Brisbane, Australia</a></li>
                            </ul>
                            <div class="custom-social">
                                <li><a href="#"><span class="fa fa-brands fa-facebook-f"></span></a></li>
                                <li><a href="#"><span class="fa fa-brands fa-twitter"></span></a></li>
                                <li><a href="#"><span class="fa fa-brands fa-instagram"></span></a></li>
                                <li><a href="#"><span class="fa fa-brands fa-linkedin"></span></a></li>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <hr>

            <!-- copyright -->
            <div class="row my-2 justify-content-center">
                <div class="col-auto">
                    <p class="text-center text-lg-start">
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script>.
                        Soarair. All Rights Reserved.
                    </p>
                </div>
            </div>
    </footer>
    <!-- End footer section -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

soarair/templates/index.html
{% extends 'base.html' %}

{% block head %}
<div class="hero">
    <div class="container-fluid">
        <div class="container">
            <div class="col-md-4">
                <div class="intro-excerpt">
                    <h1>Soarair <span class="d-block">Merchandise</span></h1>
                    <p class="mb-4">
                        Shop our exclusive kids line of luggage, fashion, toys and more using your Soarair Loyalty
                        Points.
                        Choose a treat to inspire a young adventurer.
                    </p>
                    <a href="#categoryList" class="btn btn-light">Shop Now</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block main %}

<!-- Start New Arrivals Section -->
<div class="arrivals-section">
    <div class="container px-5">
        <div class="row mb-5">
            <div class="col-md-12">
                <h2 class="section-title mb-4">New Arrivals</h2>
                <hr>
            </div>
        </div>

        <div class="row">
            {% for arrival in newarrivals %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-4 mb-4">
                <div class="item-entry">
                    <a href="{{ url_for('main.product', category=arrival.category_id, productid=arrival.id) }}"
                        class="item-thumbnail">
                        <img src="{{ url_for('static', filename='img/'+arrival.image1) }}"
                            class="img-fluid w-100 h-auto" alt="Image">
                    </a>
                    <div class="item-desc text-center">
                        <h3>
                            <a href="{{ url_for('main.product', category=arrival.category_id, productid=arrival.id) }}">
                                <strong>{{ arrival.name|truncate(30) }}</strong>
                            </a>
                        </h3>
                        <!-- Product ratings -->
                        <div class="product-rating-section">
                            <span>{{ arrival.rating }}</span>
                            <span class="fa fa-star checked"></span>
                            <span>'s</span>
                        </div>
                        <!-- End product ratings -->
                        <h3 class="price-tag">${{ arrival.price }} <span>or</span> {{ arrival.points }} PTS</h3>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- End New Arrivals Section -->

<!-- Start Product DIYs Section -->
<div class="planediy-section">
    <div class="container px-5">
        <div class="row mb-5">
            <div class="col-md-3">
                <h2 class="section-title">What's On</h2>
                <hr>
            </div>
        </div>
        <div class="row justify-content-start">
            <div class="col-lg-5 mb-5 mb-lg-0">
                <div class="imgs-grid">
                    <div class="grid grid-1"><img src="{{url_for('static', filename='img/diy2.jpg')}}" alt="planeimage">
                    </div>
                    <div class="grid grid-2"><img src="{{url_for('static', filename='img/diy1.jpg')}}" alt="planeimage">
                    </div>
                </div>
            </div>
            <div class="col-lg-4 ps-lg-5">
                <h1 class="section-title mb-4">Design your own planes</h1>
                <p>Keep your kids busy this holiday with fun and educational plane modelling and crafting activities to
                    spark imagination!</p>
                <a href="#categoryList" class="btn btn-primary">Check out DIYs Here</a>
            </div>
            <div class="col-lg-3 ps-lg-5">
                <div class="globe-img">
                    <img src="{{url_for('static', filename='img/Icons/globe.png')}}" alt="Image" class="img-fluid">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Product DIYs Section -->

<!-- Start Browse Category Section -->
<div class="category-section" id="categoryList">
    <div class="container px-5">
        <div class="row mb-5">
            <div class="col-sm-5">
                <h2 class="section-title">Browse Merchandise Range</h2>
                <hr>
            </div>
        </div>
        <div class="row justify-content-end">
            <div class="card-deck">
                {% for category in categories%}
                <div class="col-lg-4 col-md-6">
                    <div class="card shadow">
                        <div class="inner">
                            <img class="card-img-top" src="{{url_for('static', filename='img/'+category.image)}}"
                                alt="{{category.name}}">
                        </div>
                        <div class="card-body text-center">
                            <h5 class="card-title">{{category.name}}</h5>
                            <p class="card-text">
                                {{category.description}} </p>
                            <a href="{{ url_for('main.shop', categoryid=category.id) }}" class="btn btn-secondary">View
                                More</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<!-- End Browse Category Section -->

<!-- Start Ordering info section  -->
<div class="ordering-info-section">
    <div class="container px-4 text-center">
        <h4>Order Tracking</h4>
        <p class="mb-4">
            Follow your package from clicking the order button to shipment,
            so you know exactly when it will arrive at your doorstep.
        </p>
        <h4>Express Ordering</h4>
        <p class="mb-4">
            Reorder any of your past purchases with a few quick clicks.
            Save your address information to make new orders ASAP.
        </p>
    </div>
</div>
{% endblock %}

soarair/templates/order.html
{% extends 'base.html' %}

{% block main %}
<!-- Start Cart Section -->
<div class="cart-section mt-5">
    <div class="container px-4">
        <!-- section title -->
        <div class="row mb-5">
            <div class="col">
                <h2 class="section-title">Cart</h2>
                <hr>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-12">
                <div class="order-table">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="product-thumbnail">Image</th>
                                <th class="product-name">Product</th>
                                <th class="product-price">Unit $</th>
                                <th class="product-price">Unit PTS</th>
                                <th class="product-remove">Remove</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for product in order.products %}
                            <tr>
                                <td class="product-thumbnail">
                                    <img src="{{url_for('static', filename='img/'+product.image1)}}"
                                        alt="{{product.name}}" class="img-fluid img-thumbnail">
                                    <!-- style="max-width: 50%!important; max-height: 30% !important;"> -->
                                </td>
                                <td class="product-name">
                                    <h2 class="h6 text-black">{{product.name}}</h2>
                                </td>
                                <td>{{product.price}}</td>
                                <td>{{product.points}}</td>
                                <td>
                                    <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                                        <input type="hidden" id="id" name="id" value="{{product.id}}">
                                        <input type="submit" value="X" class="btn btn-primary mb-3">
                                </td>
                                </form>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <!-- Button and navigations -->
        <div class="row">
            <div class="col-md-12">
                <div class="row mb-5 d-flex justify-content-center">
                    <div class="col-md-3 col-sm-6 mb-3 mb-md-0 text-center">
                        <a href="{{ url_for('main.deleteorder') }}">
                            <button class="btn btn-primary btn-sm">Delete Cart</button>
                        </a>
                    </div>
                    <div class="col-md-3 col-sm-6 mb-3 mb-md-0 text-center">
                        <a href="{{ url_for('main.index', _anchor='categoryList') }}">
                            <button class="btn btn-primary btn-sm">Shop More</button>
                        </a>
                    </div>
                    <div class="col-md-3 col-sm-6 text-center">
                        <a href="{{ url_for('main.checkout', total_cost=cost, total_points = point) }}">
                            <button class="btn btn-primary btn-sm">Checkout</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Cart Section -->
{% endblock %}

soarair/templates/shop.html
{% extends 'base.html' %}
{% block main %}
<div class="product-section px-4">
    <div class="container">
        <div class="row mb-5">
            <div class="col">
                {% for x in category%}
                <h2 class="section-title">{{x.name}}</h2>
                {% endfor %}
                <hr>
                <div class="d-lg-flex pt-2 row justify-content-center">
                    <!-- ratio select -->
                    <div class="form-check form-check-inline align-items-center my-2 mx-2 mr-lg-2 filter bg-warning border">
                        {% for c in category%}
                        <a href="{{ url_for('main.shopnew', categoryid=c.id) }}">
                            <!-- <input class=" form-check-input" type="radio" name="inlineRadioOptions"
                                    id="inlineRadio1" value="option1"> -->
                            {% endfor %}
                            <label class="form-check-label" for="inlineRadio1"> New Arrivals</label>
                        </a>
                        <!-- </button> -->
                    </div>
                    <div class="form-check form-check-inline align-items-center my-2 mx-2 mr-lg-2 filter bg-warning border">
                        <!-- <input class="form-check-input ml-3" type="radio" name="inlineRadioOptions" id="inlineRadio2"
                            value="option2"> -->
                        {% for i in category%}
                        <a href="{{ url_for('main.shophighrate', categoryid=i.id) }}">
                            {% endfor %}
                            <label class="form-check-label" for="inlineRadio2"> Highest Rated</label>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-between">
            <div class="card-deck">
                {% for product in products%}
                <div class="col-12 col-md-6 col-lg-4 col-xl-3 mb-5">
                    <div class="card shadow">
                        <div class="inner">
                            <img class="card-img-top" src="{{url_for('static', filename='img/'+product.image1)}}"
                                alt="{{product.name}}">
                        </div>
                        <div class="card-body text-center">
                            <h5 class="card-title">{{product.name|truncate(45)}}</h5>
                            <p class="card-text">{{product.description|truncate(70)}}</p>
                            <p>
                                <!-- Product ratings -->
                            <div class="product-rating-section">
                                <span>{{product.rating}}</span>
                                <span class="fa fa-star checked"></span>
                                <span>'s</span>
                            </div>
                            <!-- End product ratings -->
                            <h5 class="price-tag">${{product.price}} <span>or</span> {{product.points}} PTS</h5>
                            </p>
                            {% for i in category%}
                            <a href="{{ url_for('main.product', category=i.id, productid=product.id) }}"
                                class="btn btn-sm btn-secondary py-2 mb-2 mt-2">View More</a>
                            {% endfor %}
                            <form action="{{ url_for('main.order') }}">
                                <input type="hidden" id="product_id" name="product_id" value="{{product.id}}">
                                <input type="submit" class="btn btn-secondary py-2 mt-2" value="Buy Now">
                            </form>
                        </div> 
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

soarair/templates/thankyou.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
    <div class="row my-5">
        <div class="col-md-12 text-center pt-5">
            <h1 class="display-3 text-black">Thank you!</h1>
            <p class="lead mb-5">Your order was successfuly completed.</p>
            <span class="display-3 thankyou-icon text-primary">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart-check mb-5" fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M11.354 5.646a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708 0z" />
                    <path fill-rule="evenodd"
                        d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                </svg>
            </span>
            <p><a href="{{ url_for('main.index') }}" class="btn btn-sm py-2 btn-primary">Back to Home</a></p>
        </div>
    </div>
</div>
{% endblock %}